export const MAP_TIMING = {
  FITBOUNDS_DEBOUNCE_MS: 300,

  ZOOM_ANIMATION_MS: 450,

  FITBOUNDS_PADDING_PX: 50,

  TOOLTIP_DELAY_MS: 100,

  MIN_SKELETON_DISPLAY_MS: 500,

  MAX_WAIT_FOR_DATA_MS: 5000,

  FACET_CELL_RENDER_PIXEL_RATIO_MAX: 1,

  MAPLIBRE_SYNC_EPSILON: 1e-4,

  MAP_RESIZE_DEBOUNCE_MS: 150,

  LAYER_UPDATE_DEBOUNCE_MS: 16,

  PROJECT_EMPTY_RESET_DEBOUNCE_MS: 250
} as const;
