import {
  DEFAULT_VISUALIZATION_COLOR,
  DEFAULT_VISUALIZATION_NEUTRAL_COLOR
} from '$lib/features/commons/constants/colors.constants';

export const VIZ_SUBLAYER_COLOR = DEFAULT_VISUALIZATION_COLOR;
export const BASEMAP_SUBLAYER_COLOR = DEFAULT_VISUALIZATION_NEUTRAL_COLOR;
