export const GEO_DETECTION = {
  MIN_CONFIDENCE: 0.5,
  HIGH_CONFIDENCE: 0.8,
  MATCH_THRESHOLD: 0.8,
  VERY_HIGH_CONFIDENCE: 0.85,
  NEAR_CERTAIN: 0.9,
  EXCEPTIONAL: 0.95,
  MULTIPLIER_STRONG: 1.5,
  MULTIPLIER_MODERATE: 0.8,
  LOW_MATCH_THRESHOLD: 0.4,
  MEDIUM_MATCH_THRESHOLD: 0.3,
  SAMPLE_VALUE_COUNT: 5,
  VALUE_TYPE_OVERRIDE_MARGIN: 0.15,
  NUMERIC_GEO_TEXT_SHARE_LIMIT: 0.8,
  COUNTRY_HEADER_CONFIDENCE: 0.75,
  COUNTRY_WEAK_HEADER_CONFIDENCE: 0.6,
  REGION_HEADER_CONFIDENCE: 0.75,
  CITY_HEADER_CONFIDENCE: 0.72,
  COORDINATES_HEADER_CONFIDENCE: 0.7,
  GPS_SWAPPED_MIN_OUT_OF_RANGE_SHARE: 0.5,
  GPS_SWAP_MIN_SAMPLE_COUNT: 2,
  EUROPE_LONGITUDE_MAX_ABS: 15,
  EUROPE_LATITUDE_MIN_ABS: 40,
  EUROPE_LATITUDE_MAX_ABS: 90
} as const;

export const DATA_VALIDATION = {
  NULL_PERCENTAGE_THRESHOLD: 50,
  MIN_YEAR: 1900,
  MAX_YEAR: 2100,
  ANOMALY_MULTIPLIER: 0.8
} as const;

export const NULL_VALUE_TOKENS = [
  '',
  ':',
  '-',
  '...',
  'null',
  'NULL',
  'NA',
  'N/A',
  'n/a',
  '#N/A',
  'NaN',
  'nil',
  'NIL',
  'none',
  'NONE',
  'None'
] as const;

export const FUZZY_SEARCH = {
  DEFAULT_SIMILARITY: 0.85,
  HEAD_TAIL_THRESHOLD: 0.4
} as const;
